version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shreyank
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    restart: always

  migration:
    build:
      context: ./users
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=blog_platform.settings
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    entrypoint: ["/usr/bin/tini", "--"]
    command: >
      sh -c "python manage.py migrate"
    restart: "on-failure"

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=blog_platform.settings
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
      - migration
    entrypoint: ["/usr/bin/tini", "--"]
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: "on-failure"

  blogs:
    build:
      context: ./blogs
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=blog_platform.settings
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
      - migration
    entrypoint: ["/usr/bin/tini", "--"]
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: "on-failure"

  comments:
    build:
      context: ./comments
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=blog_platform.settings
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
      - migration
    entrypoint: ["/usr/bin/tini", "--"]
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: "on-failure"

volumes:
  postgres_data:
